sudo: required
dist: trusty
language: java
jdk:
    - oraclejdk8
    - oraclejdk11
    
env:
    - RUNTIME=ol BUILD_TOOL=maven
#    - RUNTIME=wlp BUILD_TOOL=maven
    - RUNTIME=tomee BUILD_TOOL=maven
# - RUNTIME=ol RUNTIME_VERSION=19.0.0.2 BUILD_TOOL=gradle
# - RUNTIME=wlp RUNTIME_VERSION=19.0.0.2 BUILD_TOOL=gradle
# - RUNTIME=ol RUNTIME_VERSION=19.0.0.3 BUILD_TOOL=gradle
# - RUNTIME=wlp RUNTIME_VERSION=19.0.0.3 BUILD_TOOL=gradle
cache:
    directories:
        - $HOME/.m2
services:
    - docker
before_install:
     - echo "Deleting old .m2 artifacts..."
     - rm -rf $HOME/.m2/repository/net/wasdev
     - rm -rf $HOME/.m2/repository/io/openliberty
     - echo 'Installing ci.common lib ....'
     - git clone https://github.com/wasdev/ci.common.git ./ci.common
     - cd ./ci.common
     - mvn clean install
     - cd ..
     - echo "Installing ci.gradle lib ..."
     - git clone https://github.com/wasdev/ci.gradle.git ./ci.gradle
     - cd ./ci.gradle
     - ./gradlew clean install
     - cd ..
     - docker run -d -p 5000:5000 --restart=always --name registry registry:2
install: true
before_script:
    - sudo /etc/init.d/mysql stop
script:
    - cd boost-common
    - mvn install -Dinvoker.streamLogs=true
    - cd ../boost-maven
    - mvn install -Dinvoker.streamLogs=true
    - cd ..
    - |
      if [ "$BUILD_TOOL" = "maven" ]; then
          export CD_COMMAND="cd boost-maven";
          export TEST_COMMAND="mvn install -Pit -DboostRuntime=$RUNTIME";
      else
          export CD_COMMAND="cd boost-gradle";
          export TEST_COMMAND="./gradle-test.sh"
      fi;
    - ./travis.sh
after_failure:
    - cat boost-maven/boost-maven-plugin/target/it/test-dev-release/build.log
